# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    network_mode: host
    image: mariadb
    # ports:
      # - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
