# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    network_mode: host
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  apache:
    network_mode: host
    image: docker_apache
    restart: always
    volumes:
      - "../httpd:"